version: '2.0'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: 'db_password'


    web:
        image: django
        build: .
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - db
        command: bash -c "cd ./cidAPI && ./manage.py migrate && ./cidAPI/manage.py runserver 0.0.0.0:8000" 
        environment:
            IN_DOCKER: 1


    frontend:
        image: node
        volumes:
            - ./cidAPI/static:/frontend
        working_dir: /frontend
        command: bash -c "npm install -g serve && serve -p 80"
        ports:
            - "80:80"
        depends_on:
            - db
            - web
            - minio


    minio:
        image: minio/minio
        volumes:
            - ../data:/export
        ports:
            - "9001:9000"
        environment:
            MINIO_ACCESS_KEY: test_access
            MINIO_SECRET_KEY: test_secret
        command: server /export
