version: '3.2'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: 'db_password'
        #volumes:
            #- ./dbdata:/var/lib/postgresql/data
        
    web:
        image: django
        build: .
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - db
        command: ["./cidAPI/manage.py","runserver","0.0.0.0:8000"]
        environment:
            IN_DOCKER: 1
