version: '3.2'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: 'db_password'
        #volumes:
            #- ./dbdata:/var/lib/postgresql/data
        
    web:
        image: django
        build: .
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - db
        command: ["./cidAPI/manage.py","runserver","0.0.0.0:8000"]
        environment:
            IN_DOCKER: 1
    minio:
        image: minio/minio
        volumes:
            - ../data:/export
        ports:
            - "9001:9000"
        environment:
            MINIO_ACCESS_KEY: test_access
            MINIO_SECRET_KEY: test_secret
        command: server /export
